# Create a program that reads something via keyboard and displays its primitive type and all possible information about it on the screen.
something = input("Enter something: ")
print("The primitive type of this value is: {}.".format(type(something)))
print("Is alphanumeric? {}".format(something.isalnum()))
print("Is alphabetic? {}".format(something.isalpha()))
print("Is ASCII? {}".format(something.isascii()))
print("Is decimal? {}".format(something.isdecimal()))
print("Is digit? {}".format(something.isdigit()))
print("Is identifier? {}".format(something.isidentifier()))
print("Is lowercase? {}".format(something.islower()))
print("Is numeric? {}".format(something.isnumeric()))
print("Is printable? {}".format(something.isprintable()))
print("Are there only spaces? {}".format(something.isspace()))
print("Is title? {}".format(something.istitle()))
print("Is uppercase? {}".format(something.isupper()))
